// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Slice Zone field in *Footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
	 * Meta Title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: footer.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: footer.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

/**
 * Item in *Header → Header Navigation*
 */
export interface HeaderDocumentDataHeaderNavigationItem {
	/**
	 * Link field in *Header → Header Navigation*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.header_navigation[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Link Label field in *Header → Header Navigation*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.header_navigation[].link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_label: prismic.KeyTextField;
}

type HeaderDocumentDataSlicesSlice = never;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Header Navigation field in *Header*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.header_navigation[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	header_navigation: prismic.GroupField<Simplify<HeaderDocumentDataHeaderNavigationItem>>;

	/**
	 * Menu Label First field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_label_first
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	menu_label_first: prismic.KeyTextField;

	/**
	 * Menu Label Second field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_label_second
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	menu_label_second: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Header*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
	 * Meta Title field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: header.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: header.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| ApproachSliceSlice
	| WorkListSlice
	| FeaturedTextSlice
	| HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
	/**
	 * Slice Zone field in *Settings*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
	 * Meta Title field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: settings.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: settings.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SettingsDocumentData>,
	'settings',
	Lang
>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | PageDocument | SettingsDocument;

/**
 * Primary content in *ApproachSlice → Default → Primary*
 */
export interface ApproachSliceSliceDefaultPrimary {
	/**
	 * Title field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Paragraph field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * Cta Link field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * Cta Link Label field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.cta_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_link_label: prismic.KeyTextField;

	/**
	 * Content Title field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.content_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content_title: prismic.RichTextField;

	/**
	 * Content Paragraph field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.content_paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content_paragraph: prismic.RichTextField;

	/**
	 * Content Title Second field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.content_title_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content_title_second: prismic.RichTextField;

	/**
	 * Content Paragraph Second field in *ApproachSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: approach_slice.default.primary.content_paragraph_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content_paragraph_second: prismic.RichTextField;
}

/**
 * Default variation for ApproachSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApproachSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ApproachSliceSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ApproachSlice*
 */
type ApproachSliceSliceVariation = ApproachSliceSliceDefault;

/**
 * ApproachSlice Shared Slice
 *
 * - **API ID**: `approach_slice`
 * - **Description**: ApproachSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ApproachSliceSlice = prismic.SharedSlice<'approach_slice', ApproachSliceSliceVariation>;

/**
 * Primary content in *FeaturedText → Default → Primary*
 */
export interface FeaturedTextSliceDefaultPrimary {
	/**
	 * Title field in *FeaturedText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_text.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Cta Link field in *FeaturedText → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_text.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * Cta Link Label field in *FeaturedText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_text.default.primary.cta_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_link_label: prismic.KeyTextField;

	/**
	 * Paragraph field in *FeaturedText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_text.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * Paragraph Second field in *FeaturedText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_text.default.primary.paragraph_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph_second: prismic.RichTextField;
}

/**
 * Default variation for FeaturedText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeaturedTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FeaturedText*
 */
type FeaturedTextSliceVariation = FeaturedTextSliceDefault;

/**
 * FeaturedText Shared Slice
 *
 * - **API ID**: `featured_text`
 * - **Description**: FeaturedText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedTextSlice = prismic.SharedSlice<'featured_text', FeaturedTextSliceVariation>;

/**
 * Primary content in *HeroHome → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Paragraph field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * Time Location field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.time_location
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	time_location: prismic.KeyTextField;

	/**
	 * News Link field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	news_link: prismic.LinkField;

	/**
	 * News Link Label field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	news_link_label: prismic.KeyTextField;

	/**
	 * News Link Second field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link_second
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	news_link_second: prismic.LinkField;

	/**
	 * News Link Second Label field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link_second_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	news_link_second_label: prismic.KeyTextField;

	/**
	 * News Link Third field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link_third
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	news_link_third: prismic.LinkField;

	/**
	 * News Link Third Label field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.news_link_third_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	news_link_third_label: prismic.KeyTextField;

	/**
	 * Tagline field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.tagline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	tagline: prismic.KeyTextField;

	/**
	 * Info field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.info
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	info: prismic.KeyTextField;

	/**
	 * Brand field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.brand
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	brand: prismic.KeyTextField;

	/**
	 * Cta Link field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * Cta Link Label field in *HeroHome → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.cta
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta: prismic.KeyTextField;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *WorkList → Default → Primary*
 */
export interface WorkListSliceDefaultPrimary {
	/**
	 * Title field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;

	/**
	 * Cta Link field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * Cta Link Label field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.cta_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_link_label: prismic.KeyTextField;

	/**
	 * Work Link field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	work_link: prismic.LinkField;

	/**
	 * Work Image field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	work_image: prismic.ImageField<never>;

	/**
	 * Work Title field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_title: prismic.RichTextField;

	/**
	 * Work Description field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_description: prismic.RichTextField;

	/**
	 * Work Cta Link field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	work_cta_link: prismic.LinkField;

	/**
	 * Work Cta Link Label field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_cta_link_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_cta_link_label: prismic.KeyTextField;

	/**
	 * Work Label field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_label
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_label: prismic.RichTextField;

	/**
	 * Work Link Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_link_second
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	work_link_second: prismic.LinkField;

	/**
	 * Work Image Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_image_second
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	work_image_second: prismic.ImageField<never>;

	/**
	 * Work Title Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_title_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_title_second: prismic.RichTextField;

	/**
	 * Work Description Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_description_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_description_second: prismic.RichTextField;

	/**
	 * Work Cta Link Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_cta_link_second
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	work_cta_link_second: prismic.LinkField;

	/**
	 * Work Cta Link Label Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_cta_link_label_second
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	work_cta_link_label_second: prismic.KeyTextField;

	/**
	 * Work Label Second field in *WorkList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: work_list.default.primary.work_label_second
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	work_label_second: prismic.RichTextField;
}

/**
 * Default variation for WorkList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkListSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<WorkListSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *WorkList*
 */
type WorkListSliceVariation = WorkListSliceDefault;

/**
 * WorkList Shared Slice
 *
 * - **API ID**: `work_list`
 * - **Description**: WorkList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkListSlice = prismic.SharedSlice<'work_list', WorkListSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataSlicesSlice,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataHeaderNavigationItem,
			HeaderDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSlicesSlice,
			AllDocumentTypes,
			ApproachSliceSlice,
			ApproachSliceSliceDefaultPrimary,
			ApproachSliceSliceVariation,
			ApproachSliceSliceDefault,
			FeaturedTextSlice,
			FeaturedTextSliceDefaultPrimary,
			FeaturedTextSliceVariation,
			FeaturedTextSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			WorkListSlice,
			WorkListSliceDefaultPrimary,
			WorkListSliceVariation,
			WorkListSliceDefault
		};
	}
}
