// Code generated by Slice Machine. DO NOT EDIT.

import FeaturedText from './FeaturedText/index.svelte';
import HomeHero from './HomeHero/index.svelte';

export const components = {
	featured_text: FeaturedText,
	hero: HomeHero
};
