// Code generated by Slice Machine. DO NOT EDIT.

import ApproachSlice from './ApproachSlice/index.svelte';
import FeaturedText from './FeaturedText/index.svelte';
import HeroHome from './HeroHome/index.svelte';
import WorkList from './WorkList/index.svelte';

export const components = {
	approach_slice: ApproachSlice,
	featured_text: FeaturedText,
	hero: HeroHome,
	work_list: WorkList
};
